<?php

return [
    'premissions' => [
        'main' => 'الرئيسية',
        'setting_change' => 'الإعدادات العامة',
        'notifications' => 'الإشعارات',
        'roles' => 'الأدوار والصلاحيات',
        'addRole' => 'إضافة دور جديد',
        'editRole' => 'تعديل الدور',
        'deleteRole' => 'حذف الدور',
        'employee' => 'الموظفون',
        'addEmployee' => 'إضافة موظف',
        'editEmployee' => 'تعديل موظف',
        'deleteEmployee' => 'حذف موظف',
        'admins' => 'المديرون',
        'addAdmin' => 'إضافة مدير',
        'editAdmin' => 'تعديل مدير',
        'deleteAdmin' => 'حذف مدير',
        'categories' => 'الأقسام',
        'addCategory' => 'إضافة قسم',
        'editCategory' => 'تعديل قسم',
        'deleteCategory' => 'حذف قسم',
        'sliders' => 'السلايدر',
        'addSlider' => 'إضافة سلايدر',
        'editSlider' => 'تعديل سلايدر',
        'deleteSlider' => 'حذف سلايدر',
        'splaches' => 'شاشات البداية',
        'addSplach' => 'إضافة شاشة بداية',
        'editSplach' => 'تعديل شاشة بداية',
        'deleteSplach' => 'حذف شاشة بداية',
        'about' => 'من نحن',
        'editAbout' => 'تعديل من نحن',
        'terms' => 'الشروط',
        'editTerms' => 'تعديل الشروط',
        'privacies' => 'سياسة الخصوصية',
        'editPrivacies' => 'تعديل سياسة الخصوصية',
        'socials' => 'وسائل التواصل الاجتماعي',
        'addSocial' => 'إضافة وسيلة تواصل',
        'editSocial' => 'تعديل وسيلة تواصل',
        'deleteSocial' => 'حذف وسيلة تواصل',
    ],
];
