<?php

return
    [
    'premissions' =>
    [
        'main' => 'Main',
        'setting_change' => 'General Settings',
        'notifications' => 'Notifications',
        'roles' => 'Roles & Permissions',
        'addRole' => 'Add New Role',
        'editRole' => 'Edit Role',
        'deleteRole' => 'Delete Role',
        'employee' => 'Employees',
        'addEmployee' => 'Add Employee',
        'editEmployee' => 'Edit Employee',
        'deleteEmployee' => 'Delete Employee',
        'admins' => 'Admins',
        'addAdmin' => 'Add Admin',
        'editAdmin' => 'Edit Admin',
        'deleteAdmin' => 'Delete Admin',
        'categories' => 'Categories',
        'addCategory' => 'Add Category',
        'editCategory' => 'Edit Category',
        'deleteCategory' => 'Delete Category',
        'sliders' => 'Sliders',
        'addSlider' => 'Add Slider',
        'editSlider' => 'Edit Slider',
        'deleteSlider' => 'Delete Slider',
        'splaches' => 'Splaches',
        'addSplach' => 'Add Splach',
        'editSplach' => 'Edit Splach',
        'deleteSplach' => 'Delete Splach',
        'about' => 'About',
        'editAbout' => 'Edit About',
        'terms' => 'Terms',
        'editTerms' => 'Edit Terms',
        'privacies' => 'Privacies',
        'editPrivacies' => 'Edit Privacies',
        'socials' => 'Socials',
        'addSocial' => 'Add Socials',
        'editSocial' => 'Edit Socials',
        'deleteSocial' => 'Delete Socials',
    ],
];
